# Pandas Data Cleaning Portfolio Project

## üßπ Professional Data Cleaning & Analysis Showcase

**Author:** Teslim Adeyanju  
**Date:** September 2025  
**Focus:** Advanced Pandas data cleaning and preprocessing techniques

---

This notebook demonstrates professional-grade data cleaning techniques using two real-world datasets:
1. **Climate Data**: Global land temperature measurements
2. **Economic Data**: GDP per capita by metropolitan areas

---

## üìã Table of Contents
1. [Environment Setup](#setup)
2. [Climate Data Cleaning](#climate)
3. [Economic Data Cleaning](#economic)
4. [Key Takeaways](#takeaways)

---

## 1. Environment Setup {#setup}

### Import Libraries and Configure Display Options

Setting up our working environment with proper display configurations for better data visualization and analysis.

In [2]:
# Import essential libraries
import pandas as pd
import numpy as np

print("‚úÖ Libraries imported successfully!")
print(f"Pandas version: {pd.__version__}")

‚úÖ Libraries imported successfully!
Pandas version: 2.1.4
‚úÖ Libraries imported successfully!
Pandas version: 2.1.4

In [3]:
# Configure pandas display options for better data visualization
pd.options.display.float_format = '{:,.2f}'.format  # Format floats with 2 decimal places

# Set comprehensive display options
pd.set_option('display.max_columns', None)    # Show all columns
pd.set_option('display.width', None)          # No width limit
pd.set_option('display.max_colwidth', None)   # Show full column content

print("‚úÖ Display options configured for optimal viewing")

‚úÖ Display options configured for optimal viewing
‚úÖ Display options configured for optimal viewing

---

## 2. Climate Data Cleaning {#climate}

### Dataset: Global Land Temperature Measurements

**Objective**: Clean and prepare temperature data from weather stations worldwide.

**Key Cleaning Tasks**:
- Parse date components into proper datetime format
- Assign meaningful column names
- Optimize data types for memory efficiency
- Validate data structure

In [4]:
# Load climate data with advanced parameters
landtemps = pd.read_csv('data/landtempssample.csv',
    names=['stationid','year','month','avgtemp','latitude',
      'longitude','elevation','station','countryid','country'],  # Custom column names
    skiprows=1,                    # Skip header row
    parse_dates=[['month','year']], # Automatically combine and parse date columns
    low_memory=False               # Prevent data type inference issues
)

print("‚úÖ Climate data loaded successfully!")
print(f"Dataset shape: {landtemps.shape}")
print(f"Data type: {type(landtemps)}")

<positron-console-cell-4>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

‚úÖ Climate data loaded successfully!
Dataset shape: (100000, 9)
Data type: <class 'pandas.core.frame.DataFrame'>
‚úÖ Climate data loaded successfully!
Dataset shape: (100000, 9)
Data type: <class 'pandas.core.frame.DataFrame'>

In [5]:
# Display first few rows to understand data structure
print("üìä First 5 rows of climate data:")
display(landtemps.head())

üìä First 5 rows of climate data:
üìä First 5 rows of climate data:

  month_year    stationid  avgtemp  latitude  longitude  elevation           station countryid        country
0 2000-04-01  USS0010K01S     5.27     39.90    -110.75   2,773.70     INDIAN_CANYON        US  United States
1 1940-05-01  CI000085406    18.04    -18.35     -70.33      58.00             ARICA        CI          Chile
2 2013-12-01  USC00036376     6.22     34.37     -91.12      61.00     SAINT_CHARLES        US  United States
3 1963-02-01  ASN00024002    22.93    -34.28     140.60      65.50  BERRI_IRRIGATION        AS      Australia
4 2001-11-01  ASN00028007      NaN    -14.78     143.50      79.40          MUSGRAVE        AS      Australia

In [6]:
# Analyze data structure and quality
print("üîç Data Structure Analysis:")
print("="*50)
landtemps.info()
print("\n‚úÖ Climate data cleaning completed successfully!")

üîç Data Structure Analysis:
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   month_year  100000 non-null  datetime64[ns]
 1   stationid   100000 non-null  object
 2   avgtemp     85554 non-null   float64
 3   latitude    100000 non-null  float64
 4   longitude   100000 non-null  float64
 5   elevation   100000 non-null  float64
 6   station     100000 non-null  object
 7   countryid   100000 non-null  object
 8   country     99995 non-null   object
dtypes: datetime64[ns](1), float64(4), object(4)
memory usage: 6.9+ MB

‚úÖ Climate data cleaning completed successfully!
üîç Data Structure Analysis:
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   month_year  100000 non-null  datetime64[ns]
 1   stationid   100000 non-null  object
 2   avgtemp     85554 non-null   float64
 3   latitude    100000 non-null  float64
 4   longitude   100000 non-null  float64
 5   elevation   100000 non-null  float64
 6   station     100000 non-null  object
 7   countryid   100000 non-null  object
 8   country     99995 non-null   object
dtypes: datetime64[ns](1), float64(4), object(4)
memory usage: 6.9+ MB

‚úÖ Climate data cleaning completed successfully!

---

## 3. Economic Data Cleaning {#economic}

### Dataset: GDP Per Capita by Metropolitan Areas

**Objective**: Clean and prepare GDP data from Excel file with complex formatting.

**Key Cleaning Tasks**:
- Handle Excel file with specific sheet and range selection
- Clean column names and remove unnecessary whitespace
- Convert text data to appropriate numeric formats
- Handle missing values appropriately

In [7]:
percapitaGDP_raw = pd.read_excel('data/GDPpercapita.xlsx', sheet_name=1)
print(f"Raw data shape: {percapitaGDP_raw.shape}")
display(percapitaGDP_raw.head())

Raw data shape: (707, 20)
Raw data shape: (707, 20)

,NaN,"Sorry, the query is too large to fit into the Excel cell. You will not be able to update your table with the .Stat Populator.",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Dataset: Metropolitan areas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Variables,NaN,"GDP per capita (USD, constant prices, constant PPP, base year 2015)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Unit,NaN,US Dollar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Year,NaN,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
4,Metropolitan areas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 2: Advanced Excel Processing

Now we'll apply proper data cleaning techniques to extract only the relevant data with appropriate formatting.

In [8]:
# Advanced Excel processing with precise parameters
percapitaGDP = pd.read_excel('data/GDPpercapita.xlsx', 
    sheet_name=1,          # Select specific sheet
    skiprows=4,            # Skip header rows we don't need
    skipfooter=1,          # Skip footer row
    usecols="A, C:T"       # Select only relevant columns (A and C through T)
)

print(f"Cleaned data shape: {percapitaGDP.shape}")
display(percapitaGDP.head())

Cleaned data shape: (702, 19)
Cleaned data shape: (702, 19)

                         Year   2001   2002   2003   2004   2005   2006   2007   2008   2009   2010   2011   2012   2013   2014   2015   2016   2017   2018
0          Metropolitan areas    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
1              AUS: Australia     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..
2       AUS01: Greater Sydney  43313  44008  45424  45837  45423  45547  45880  45225  45900  45672  46535  47350  47225  48510  50075  50519  50578  49860
3    AUS02: Greater Melbourne  40125  40894  41602  42188  41484  41589  42316  40975  41384  40943  41165  41264  41157  42114  42928  42671  43025  42674
4     AUS03: Greater Brisbane  37580  37564  39080  40762  42976  44475  44635  46192  43507  42774  44166  43764  43379  43754  44388  45723  46876  46640

In [9]:
# Check data structure before cleaning
print("üîç Data structure before cleaning:")
percapitaGDP.info()
print(f"\nColumn names: {list(percapitaGDP.columns)}")

üîç Data structure before cleaning:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    702 non-null    object
 1   2001    701 non-null    object
 2   2002    701 non-null    object
 3   2003    701 non-null    object
 4   2004    701 non-null    object
 5   2005    701 non-null    object
 6   2006    701 non-null    object
 7   2007    701 non-null    object
 8   2008    701 non-null    object
 9   2009    701 non-null    object
 10  2010    701 non-null    object
 11  2011    701 non-null    object
 12  2012    701 non-null    object
 13  2013    701 non-null    object
 14  2014    701 non-null    object
 15  2015    701 non-null    object
 16  2016    701 non-null    object
 17  2017    701 non-null    object
 18  2018    701 non-null    object
dtypes: object(19)
memory usage: 104.3+ KB

Column names: ['Year', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018']
üîç Data structure before cleaning:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    702 non-null    object
 1   2001    701 non-null    object
 2   2002    701 non-null    object
 3   2003    701 non-null    object
 4   2004    701 non-null    object
 5   2005    701 non-null    object
 6   2006    701 non-null    object
 7   2007    701 non-null    object
 8   2008    701 non-null    object
 9   2009    701 non-null    object
 10  2010    701 non-null    object
 11  2011    701 non-null    object
 12  2012    701 non-null    object
 13  2013    701 non-null    object
 14  2014    701 non-null    object
 15  2015    701 non-null    object
 16  2016    701 non-null    object
 17  2017    701 non-null    object
 18  2018    701 non-null    object
dtypes: object(19)
memory usage: 104.3+ KB

Column names: ['Year', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018']

### Step 3: Column Naming and Cleaning

In [10]:
# Rename the first column to something meaningful
percapitaGDP.rename(columns={percapitaGDP.columns[0]: 'metro_area'}, inplace=True)

print(f"New first column name: '{percapitaGDP.columns[0]}'")
display(percapitaGDP.head())

New first column name: 'metro_area'
New first column name: 'metro_area'

                   metro_area   2001   2002   2003   2004   2005   2006   2007   2008   2009   2010   2011   2012   2013   2014   2015   2016   2017   2018
0          Metropolitan areas    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
1              AUS: Australia     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..     ..
2       AUS01: Greater Sydney  43313  44008  45424  45837  45423  45547  45880  45225  45900  45672  46535  47350  47225  48510  50075  50519  50578  49860
3    AUS02: Greater Melbourne  40125  40894  41602  42188  41484  41589  42316  40975  41384  40943  41165  41264  41157  42114  42928  42671  43025  42674
4     AUS03: Greater Brisbane  37580  37564  39080  40762  42976  44475  44635  46192  43507  42774  44166  43764  43379  43754  44388  45723  46876  46640

### Step 4: String Data Cleaning

Let's check for and clean any whitespace issues in the metropolitan area names.

In [11]:
# Check for leading and trailing whitespace issues
print("üîç Whitespace Analysis:")
print("="*40)
print(f"Has leading spaces: {percapitaGDP.metro_area.str.startswith(' ').any()}")
print(f"Has trailing spaces: {percapitaGDP.metro_area.str.endswith(' ').any()}")

# Preview some values to see the whitespace
print(f"\nüìã Sample metropolitan area names:")
for i, name in enumerate(percapitaGDP.metro_area.head().values):
    print(f"  {i+1}. '{name}'")

üîç Whitespace Analysis:
========================================
Has leading spaces: True
Has trailing spaces: True

üìã Sample metropolitan area names:
  1. 'Metropolitan areas'
  2. 'AUS: Australia'
  3. '  AUS01: Greater Sydney'
  4. '  AUS02: Greater Melbourne'
  5. '  AUS03: Greater Brisbane'
üîç Whitespace Analysis:
========================================
Has leading spaces: True
Has trailing spaces: True

üìã Sample metropolitan area names:
  1. 'Metropolitan areas'
  2. 'AUS: Australia'
  3. '  AUS01: Greater Sydney'
  4. '  AUS02: Greater Melbourne'
  5. '  AUS03: Greater Brisbane'

In [12]:
# Clean whitespace from metropolitan area names
percapitaGDP['metro_area'] = percapitaGDP.metro_area.str.strip()

print("‚úÖ Whitespace cleaning completed!")
print("\nüìã Cleaned metropolitan area names:")
for i, name in enumerate(percapitaGDP.metro_area.head().values):
    print(f"  {i+1}. '{name}'")

‚úÖ Whitespace cleaning completed!

üìã Cleaned metropolitan area names:
  1. 'Metropolitan areas'
  2. 'AUS: Australia'
  3. 'AUS01: Greater Sydney'
  4. 'AUS02: Greater Melbourne'
  5. 'AUS03: Greater Brisbane'
‚úÖ Whitespace cleaning completed!

üìã Cleaned metropolitan area names:
  1. 'Metropolitan areas'
  2. 'AUS: Australia'
  3. 'AUS01: Greater Sydney'
  4. 'AUS02: Greater Melbourne'
  5. 'AUS03: Greater Brisbane'

### Step 5: Data Type Conversion and Column Renaming

In [13]:
# Show current column names
print("üìä Current column names:")
print("="*40)
for i, col in enumerate(percapitaGDP.columns):
    print(f"{i+1:2}. {col}")

print(f"\nüîç Data types before conversion:")
print(percapitaGDP.dtypes)

üìä Current column names:
========================================
 1. metro_area
 2. 2001
 3. 2002
 4. 2003
 5. 2004
 6. 2005
 7. 2006
 8. 2007
 9. 2008
10. 2009
11. 2010
12. 2011
13. 2012
14. 2013
15. 2014
16. 2015
17. 2016
18. 2017
19. 2018

üîç Data types before conversion:
metro_area    object
2001          object
2002          object
2003          object
2004          object
2005          object
2006          object
2007          object
2008          object
2009          object
2010          object
2011          object
2012          object
2013          object
2014          object
2015          object
2016          object
2017          object
2018          object
dtype: object
üìä Current column names:
========================================
 1. metro_area
 2. 2001
 3. 2002
 4. 2003
 5. 2004
 6. 2005
 7. 2006
 8. 2007
 9. 2008
10. 2009
11. 2010
12. 2011
13. 2012
14. 2013
15. 2014
16. 2015
17. 2016
18. 2017
19. 2018

üîç Data types before conversion:
metro_area    object
2001          object
2002          object
2003          object
2004          object
2005          object
2006          object
2007          object
2008          object
2009          object
2010          object
2011          object
2012          object
2013          object
2014          object
2015          object
2016          object
2017          object
2018          object
dtype: object

In [14]:
# Convert GDP columns to numeric and rename with meaningful prefixes
column_rename_map = {}

# Process all GDP year columns (skip the first metro_area column)
for col in percapitaGDP.columns[1:]:
    # Convert to numeric, handling invalid values gracefully
    percapitaGDP[col] = pd.to_numeric(percapitaGDP[col], errors='coerce')
    # Create new column name with prefix
    new_name = f'GDP_{col}'
    column_rename_map[col] = new_name

# Apply all column renames at once
percapitaGDP.rename(columns=column_rename_map, inplace=True)

print(f"\nüìä Final data shape: {percapitaGDP.shape}")
print(f"\nüéØ Data types after conversion:")
print(percapitaGDP.dtypes)

üìä Final data shape: (702, 19)

üéØ Data types after conversion:
metro_area     object
GDP_2001      float64
GDP_2002      float64
GDP_2003      float64
GDP_2004      float64
GDP_2005      float64
GDP_2006      float64
GDP_2007      float64
GDP_2008      float64
GDP_2009      float64
GDP_2010      float64
GDP_2011      float64
GDP_2012      float64
GDP_2013      float64
GDP_2014      float64
GDP_2015      float64
GDP_2016      float64
GDP_2017      float64
GDP_2018      float64
dtype: object


üìä Final data shape: (702, 19)

üéØ Data types after conversion:
metro_area     object
GDP_2001      float64
GDP_2002      float64
GDP_2003      float64
GDP_2004      float64
GDP_2005      float64
GDP_2006      float64
GDP_2007      float64
GDP_2008      float64
GDP_2009      float64
GDP_2010      float64
GDP_2011      float64
GDP_2012      float64
GDP_2013      float64
GDP_2014      float64
GDP_2015      float64
GDP_2016      float64
GDP_2017      float64
GDP_2018      float64
dtype: object

### Remove rows where all of the per capita GDP values are missing.

In [15]:
percapitaGDP.isnull().sum()

metro_area      0
GDP_2001      278
GDP_2002      262
GDP_2003      262
GDP_2004      262
GDP_2005      255
GDP_2006      255
GDP_2007      255
GDP_2008      247
GDP_2009      231
GDP_2010      231
GDP_2011      222
GDP_2012      222
GDP_2013      222
GDP_2014      222
GDP_2015      222
GDP_2016      222
GDP_2017      257
GDP_2018      261
dtype: int64

In [17]:
percapitaGDP.dropna(subset=percapitaGDP.columns[1:], how="all", inplace=True)

In [18]:
percapitaGDP.head()

,metro_area,GDP_2001,GDP_2002,GDP_2003,GDP_2004,GDP_2005,GDP_2006,GDP_2007,GDP_2008,GDP_2009,GDP_2010,GDP_2011,GDP_2012,GDP_2013,GDP_2014,GDP_2015,GDP_2016,GDP_2017,GDP_2018
2,AUS01: Greater Sydney,"43,313.00","44,008.00","45,424.00","45,837.00","45,423.00","45,547.00","45,880.00","45,225.00","45,900.00","45,672.00","46,535.00","47,350.00","47,225.00","48,510.00","50,075.00","50,519.00","50,578.00","49,860.00"
3,AUS02: Greater Melbourne,"40,125.00","40,894.00","41,602.00","42,188.00","41,484.00","41,589.00","42,316.00","40,975.00","41,384.00","40,943.00","41,165.00","41,264.00","41,157.00","42,114.00","42,928.00","42,671.00","43,025.00","42,674.00"
4,AUS03: Greater Brisbane,"37,580.00","37,564.00","39,080.00","40,762.00","42,976.00","44,475.00","44,635.00","46,192.00","43,507.00","42,774.00","44,166.00","43,764.00","43,379.00","43,754.00","44,388.00","45,723.00","46,876.00","46,640.00"
5,AUS04: Greater Perth,"45,713.00","47,371.00","48,719.00","51,020.00","55,278.00","60,142.00","62,551.00","63,899.00","63,616.00","70,111.00","73,715.00","72,679.00","76,153.00","70,395.00","66,544.00","66,032.00","66,424.00","70,390.00"
6,AUS05: Greater Adelaide,"36,505.00","37,194.00","37,634.00","37,399.00","37,604.00","38,151.00","39,049.00","38,502.00","39,538.00","39,309.00","39,223.00","39,812.00","39,855.00","40,306.00","40,295.00","39,737.00","40,115.00","39,924.00"

### Set the index for the data frame using the metropolitan area column.

In [19]:
percapitaGDP.columns.to_list()

['metro_area',
 'GDP_2001',
 'GDP_2002',
 'GDP_2003',
 'GDP_2004',
 'GDP_2005',
 'GDP_2006',
 'GDP_2007',
 'GDP_2008',
 'GDP_2009',
 'GDP_2010',
 'GDP_2011',
 'GDP_2012',
 'GDP_2013',
 'GDP_2014',
 'GDP_2015',
 'GDP_2016',
 'GDP_2017',
 'GDP_2018']

In [20]:
percapitaGDP.set_index('metro_area', inplace=True)

In [21]:
percapitaGDP.head()

,GDP_2001,GDP_2002,GDP_2003,GDP_2004,GDP_2005,GDP_2006,GDP_2007,GDP_2008,GDP_2009,GDP_2010,GDP_2011,GDP_2012,GDP_2013,GDP_2014,GDP_2015,GDP_2016,GDP_2017,GDP_2018
metro_area,,,,,,,,,,,,,,,,,,
AUS01: Greater Sydney,"43,313.00","44,008.00","45,424.00","45,837.00","45,423.00","45,547.00","45,880.00","45,225.00","45,900.00","45,672.00","46,535.00","47,350.00","47,225.00","48,510.00","50,075.00","50,519.00","50,578.00","49,860.00"
AUS02: Greater Melbourne,"40,125.00","40,894.00","41,602.00","42,188.00","41,484.00","41,589.00","42,316.00","40,975.00","41,384.00","40,943.00","41,165.00","41,264.00","41,157.00","42,114.00","42,928.00","42,671.00","43,025.00","42,674.00"
AUS03: Greater Brisbane,"37,580.00","37,564.00","39,080.00","40,762.00","42,976.00","44,475.00","44,635.00","46,192.00","43,507.00","42,774.00","44,166.00","43,764.00","43,379.00","43,754.00","44,388.00","45,723.00","46,876.00","46,640.00"
AUS04: Greater Perth,"45,713.00","47,371.00","48,719.00","51,020.00","55,278.00","60,142.00","62,551.00","63,899.00","63,616.00","70,111.00","73,715.00","72,679.00","76,153.00","70,395.00","66,544.00","66,032.00","66,424.00","70,390.00"
AUS05: Greater Adelaide,"36,505.00","37,194.00","37,634.00","37,399.00","37,604.00","38,151.00","39,049.00","38,502.00","39,538.00","39,309.00","39,223.00","39,812.00","39,855.00","40,306.00","40,295.00","39,737.00","40,115.00","39,924.00"

In [22]:
percapitaGDP.transpose()

metro_area,AUS01: Greater Sydney,AUS02: Greater Melbourne,AUS03: Greater Brisbane,AUS04: Greater Perth,AUS05: Greater Adelaide,AUS07: Canberra,AT001: Vienna,AT002: Graz,AT003: Linz,AT004: Salzburg,AT005: Innsbruck,AT006: Klagenfurt,BE001: Brussels,BE002: Antwerp,BE003: Gent,BE004: Charleroi,BE005: Liege,CAN01: Toronto,CAN02: Montreal,CAN03: Vancouver,CAN04: Ottawa,CAN05: Calgary,CAN06: Edmonton,CAN07: Quebec,CAN08: Winnipeg,CAN09: Hamilton,CAN10: London,CAN11: Kitchener,CAN12: Halifax,CAN13: Victoria,CAN14: Windsor,CAN15: Saskatoon,CAN16: Sherbrooke,CH001: Zurich,CH002: Geneva,CH003: Basel,CH005: Lausanne,CL004: Antofagasta,CL006: Coquimbo-La Serena,CL010: Valparaiso,CL011: Santiago,CZ001: Prague,CZ002: Brno,CZ003: Ostrava,CZ004: Plzen,DE001: Berlin,DE002: Hamburg,DE003: Munich,DE004: Cologne,DE005: Frankfurt am Main,DE007: Stuttgart,DE008: Leipzig,DE009: Dresden,DE011: Dusseldorf,DE012: Bremen,DE013: Hanover,DE014: Nuremberg,DE017: Bielefeld,DE018: Halle an der Saale,DE019: Magdeburg,DE020: Wiesbaden,DE021: Gottingen,DE025: Darmstadt,DE026: Trier,DE027: Freiburg im Breisgau,DE028: Regensburg,DE031: Schwerin,DE032: Erfurt,DE033: Augsburg,DE034: Bonn,DE035: Karlsruhe,DE036: Monchengladbach,DE037: Mainz,DE038: Ruhr,DE039: Kiel,DE040: Saarbrucken,DE042: Koblenz,DE043: Rostock,DE044: Kaiserslautern,DE045: Iserlohn,DE052: Flensburg,DE054: Constance,DE057: Giessen,DE061: Aschaffenburg,DE064: Neubrandenburg,DE069: Rosenheim,DE073: Offenburg,DE074: Gorlitz,DE077: Schweinfurt,DE079: Wetzlar,DE083: Braunschweig-Salzgitter Wolfsburg,DE084: Mannheim-Ludwigshafen,DE504: Muenster,DE507: Aachen,DE510: Lubeck,DE513: Kassel,DE517: Osnabruck,DE520: Oldenburg (Oldenburg),DE522: Heidelberg,DE523: Paderborn,DE524: Wurzburg,DE527: Bremerhaven,DE529: Heilbronn,DE532: Ulm,DE533: Pforzheim,DE534: Ingolstadt,DE537: Reutlingen,DE540: Siegen,DE542: Hildesheim,DE544: Zwickau,DE546: Wuppertal,"DE548: Duren, Stadt","DE549: Bocholt, Stadt",DK001: Copenhagen,DK002: Aarhus,DK003: Odense,DK004: Aalborg,ES001: Madrid,ES002: Barcelona,ES003: Valencia,ES004: Seville,ES005: Saragossa,ES006: Malaga,ES008: Las Palmas,ES009: Valladolid,ES010: Palma de Mallorca,ES012: Vitoria,ES014: Pamplona,ES015: Santander,ES019: Bilbao,ES022: Vigo,ES025: Santa Cruz de Tenerife,ES501: Granada,EE001: Tallinn,FI001: Helsinki,FI002: Tampere,FI003: Turku,FI004: Oulu,FR001: Paris,FR003: Lyon,FR004: Toulouse,FR006: Strasbourg,FR007: Bordeaux,FR008: Nantes,FR009: Lille,FR010: Montpellier,FR011: Saint-Etienne,FR013: Rennes,FR014: Amiens,FR016: Nancy,FR018: Reims,FR019: Orleans,FR020: Dijon,FR021: Poitiers,FR022: Clermont-Ferrand,FR023: Caen,FR024: Limoges,FR026: Grenoble,FR030: Fort-de-France,FR032: Toulon,FR035: Tours,FR036: Angers,FR038: Le Mans,FR040: Mulhouse,FR043: Perpignan,FR203: Marseille,FR205: Nice,FR520: Les Abymes,UK001: London,UK002: West Midlands urban area,UK003: Leeds,UK004: Glasgow,UK006: Liverpool,UK007: Edinburgh,UK008: Manchester,UK009: Cardiff,UK010: Sheffield,UK011: Bristol,UK012: Belfast,UK013: Newcastle upon Tyne,UK014: Leicester,UK016: Aberdeen,UK017: Cambridge,UK018: Exeter,UK023: Portsmouth,UK025: Coventry,UK026: Kingston upon Hull,UK027: Stoke-on-Trent,UK029: Nottingham,UK030: Wirral,UK510: Sunderland,UK513: Medway,UK515: Brighton and Hove,UK516: Plymouth,UK517: Swansea,UK518: Derby,UK520: Southampton,UK525: Milton Keynes,UK528: Northampton,UK539: Bournemouth,UK546: Colchester,UK550: Dundee City,UK557: Blackburn with Darwen,UK559: Middlesbrough,UK560: Oxford,UK562: Preston,UK566: Norwich,UK568: Cheshire West and Chester,EL001: Athens,EL002: Thessaloniki,HU001: Budapest,HU005: Debrecen,HU007: Gyor,HU009: Szekesfehervar,IE001: Dublin,IE002: Cork,IT001: Rome,IT002: Milan,IT003: Naples,IT004: Turin,IT005: Palermo,IT006: Genoa,IT007: Florence,IT008: Bari,IT009: Bologna,IT010: Catania,IT011: Venice,IT012: Verona,IT022: Taranto,IT027: Cagliari,IT028: Padua,IT502: Prato,IT503: Parma,IT505: Reggio nell'Emilia,IT508: Rimini,JPN01: Tokyo,JPN02: Osaka,JPN03: Nagoya,JPN06: Sendai,JPN07: Okayama,JPN08: Hiroshima,JPN10: Naha,JPN11: Kumamoto,JPN12: Yokkaichi,JPN13: Takasaki,JPN17: Kanazawa,JPN18: Oita,JPN26: Toyama,JPN27: Kofu,JPN28: Takamatsu,JPN30: Tokushima,JPN32: Fukui,JPN33: Wakayama,JPN35: Kochi,KOR01: Seoul,KOR02: Gimhae,KOR03: Dalseong,KOR04: Gwangsan,KOR05: Seo,KOR07: Ulsan,KOR08: Heungdeok,KOR14: Jeju,LT001: Vilnius,LT002: Kaunas,LU001: Luxembourg,LV001: Riga,MEX01: Mexico City,MEX02: Guadalajara,MEX03: Monterrey,MEX08: Queretaro,MEX09: Merida,MEX14: Cuernavaca,MEX21: Aguascalientes,NL001: The Hague,NL002: Amsterdam,NL003: Rotterdam,NL004: Utrecht,NL005: Eindhoven,NL006: Tilburg,NL007: Groningen,NL008: Enschede,NL009: Arnhem,NL012: Breda,NL507: Leiden,NL511: Zwolle,NL514: Alkmaar,NO001: Oslo,NO002: Bergen,NO003: Trondheim,NO004: Stavanger,PL001: Warsaw,PL002: Lodz,PL003: Cracow,PL004: Wroclaw,PL005: Poznan,PL006: Gdansk,PL008: Bydgoszcz,PL009: Lublin,PL010: Katowice,PL011: Bialystok,PL015: Rzeszow,PL024: Czestochowa,PL506: Bielsko-Biala,PL514: Tarnow,PT001: Lisbon,PT002: Porto,PT005: Coimbra,SK001: Bratislava,SI001: Ljubljana,SI002: Maribor,SE001: Stockholm,SE002: Gothenburg,SE003: Malmo,SE006: Uppsala,USA01: New York (Greater),USA02: Los Angeles (Greater),USA03: Chicago,USA04: Washington (Greater),USA05: San Francisco (Greater),USA06: Philadelphia (Greater),USA07: Dallas,USA08: Houston,USA09: Miami (Greater),USA10: Atlanta,USA11: Boston,USA12: Phoenix,USA13: Detroit (Greater),USA14: Seattle,USA15: Minneapolis,USA16: San Diego,USA17: St. Louis,USA18: Denver,USA19: San Antonio,USA20: Portland,USA21: Cincinnati,USA22: Las Vegas,USA23: Orange,USA24: Jackson (MO),USA25: Indianapolis,USA26: Cuyahoga,USA27: New Haven,USA28: Charlotte,USA29: Sacramento,USA30: Austin,USA31: Columbus,USA32: Milwaukee,USA33: Jacksonville,USA34: Salt Lake,USA35: Tampa-Pinellas,USA36: Jefferson (KY),USA37: Memphis,USA38: Davidson,USA39: Oklahoma,USA40: Hartford,USA41: Pittsburgh,USA42: New Orleans,USA43: Virginia Beach,USA44: Erie (NY),USA45: Fresno (Greater),USA46: Richmond (Greater),USA47: Wake,USA48: Jefferson (AL),USA49: Tampa-Hillsborough,USA50: Pima,USA51: Tulsa,USA52: Albany,USA53: Providence,USA54: Albuquerque,USA55: Douglas (NE),USA56: Rochester (NY),USA57: Kern,USA58: Ventura,USA59: El Paso (TX),USA60: East Baton Rouge,USA61: Worcester,USA62: Hidalgo,USA63: Richland,USA64: Lehigh,USA65: Sarasota,USA66: Montgomery (OH),USA67: San Joaquin,USA68: Kent,USA69: Charleston,USA70: Onondaga,USA71: El Paso (CO),USA72: Ada,USA73: Hampden,USA74: Lee,USA75: Sedgwick,USA76: Polk,USA77: Dauphin,USA78: Lucas,USA79: Pulaski,USA80: Dane,USA81: Brevard,USA82: Summit,USA83: Hamilton (TN),USA84: Utah,USA85: Lancaster (PA),USA86: Stanislaus,USA87: Greene,USA88: Fayette,USA89: Spokane,USA90: Volusia-Daytona Beach,USA91: Guilford,USA92: Sonoma,USA93: Forsyth,USA94: Washoe,USA95: Ingham,USA96: Montgomery (AL),USA97: Knox,USA98: Greenville,USA99: Mahoning,USA100: Escambia,USA101: Caddo,USA102: Tulare,USA103: Newport News,USA104: York,USA105: Genesee,USA106: Jefferson (TX),USA107: Santa Barbara,USA108: Lafayette,USA109: Monterey,USA110: Mobile,USA111: Berks,USA112: Cameron,USA113: Bell,USA114: Nueces,USA115: Marion (OR),USA116: Allen,USA117: Scott,USA118: Stark,USA119: Tallahassee,USA120: Cumberland (NC),USA121: Lane,USA122: Winnebago (IL),USA123: Chatham,USA124: Vanderburgh,USA125: Washtenaw,USA126: Lubbock,USA127: Madison,USA128: Marion (FL),USA129: Peoria,USA130: Collier,USA131: Luzerne,USA132: Lancaster (NE),USA133: Thurston,USA134: Sebastian,USA135: Roanoke,USA136: Muscogee,USA137: Brown,USA138: Alachua,USA139: Larimer,USA140: Boulder,USA141: Potter,USA142: Cumberland (ME),USA143: Erie (PA),USA144: St. Lucie,USA145: Nashville,USA146: Atlantic City,USA147: McLennan,USA148: Durham,USA149: Lackawanna,USA150: St. Joseph,USA151: Santa Cruz,USA152: Webb,USA153: Minnehaha,USA154: Merced,USA155: Benton (WA),USA156: Weld,USA157: Kalamazoo,USA158: Butte,USA160: Yakima,USA161: Brazos,USA162: Tuscaloosa,USA164: Linn,USA165: Lafayette (IN),USA167: Weber,USA169: Cass,USA170: Benton (AR)
GDP_2001,"43,313.00","40,125.00","37,580.00","45,713.00","36,505.00","41,465.00","52,504.00","45,259.00","47,110.00","53,453.00","49,065.00","38,875.00","66,117.00","50,822.00","44,247.00","29,320.00","31,944.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"38,815.00","21,768.00","18,660.00","22,608.00","35,341.00","55,551.00","75,564.00","55,121.00","67,122.00","58,459.00","28,854.00","29,610.00","63,581.00","41,558.00","44,507.00","46,406.00","43,989.00","31,251.00","29,876.00","52,719.00","33,589.00","47,116.00","33,219.00","39,495.00","45,358.00","27,419.00","30,655.00","42,460.00","48,963.00","52,467.00","38,315.00","52,934.00","33,560.00","38,932.00","38,915.00","47,777.00","29,583.00","30,636.00","37,742.00","34,572.00","37,344.00","42,968.00","42,931.00","26,284.00","35,606.00","43,260.00","19,390.00","39,543.00","35,410.00","45,128.00","48,542.00","53,730.00","38,136.00","35,227.00","42,028.00","36,972.00","37,959.00","42,971.00","36,274.00","40,174.00","28,489.00","50,061.00","45,555.00","36,988.00","46,934.00","42,748.00","35,994.00","29,421.00","27,227.00","40,731.00","30,614.00","34,594.00","52,117.00","40,522.00","37,733.00","41,221.00","45,220.00","39,977.00","32,265.00","25,530.00","36,015.00","24,019.00","28,791.00","34,390.00","40,700.00","46,738.00","43,505.00","30,847.00","37,643.00","26,203.00","28,540.00","24,021.00","18,204.00","53,445.00","38,125.00","36,796.00","32,506.00","57,765.00","46,019.00","41,091.00","39,271.00","39,317.00","38,231.00","31,465.00","32,121.00","30,338.00","37,095.00","32,561.00","33,172.00","38,707.00","40,275.00","40,865.00","32,210.00","35,923.00","33,448.00","34,155.00","37,879.00","24,481.00","30,576.00","34,366.00","32,271.00","34,024.00","35,885.00","28,225.00","37,912.00","38,455.00","19,691.00","54,574.00","31,483.00","31,782.00","29,886.00","26,678.00","43,172.00","33,592.00","28,266.00","26,453.00","40,439.00","34,460.00","27,746.00","32,927.00","47,458.00","39,052.00","29,822.00","32,910.00","37,387.00","29,217.00","26,106.00","30,548.00","21,121.00","27,209.00","23,317.00","30,886.00","27,217.00","26,717.00","34,784.00","36,372.00","61,176.00","35,890.00","33,864.00","25,899.00","27,968.00","28,878.00","25,454.00","42,889.00","37,946.00","29,994.00","36,139.00","36,018.00","25,877.00","30,808.00","15,822.00","24,006.00","19,741.00",NaN,NaN,"54,674.00","58,525.00","27,567.00","46,393.00","26,172.00","46,536.00","53,312.00","31,726.00","55,533.00","27,306.00","44,077.00","46,355.00","24,577.00","33,204.00","46,627.00","47,946.00","52,466.00","53,596.00","39,860.00","43,600.00","35,298.00","39,325.00","32,192.00","33,702.00","32,942.00","24,279.00","27,441.00","32,477.00","32,582.00","40,554.00","31,392.00","36,190.00","30,961.00","32,482.00","30,454.00","35,989.00","29,236.00","27,814.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"15,983.00","10,988.00","91,488.00","18,474.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"55,098.00","58,310.00","46,015.00","60,684.00","46,606.00","38,786.00","54,300.00","34,584.00","41,418.00","45,759.00","46,038.00","39,921.00","33,940.00","57,644.00","44,840.00","39,611.00","48,833.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"41,311.00","28,073.00","26,154.00",NaN,"35,819.00","20,854.00","54,847.00","39,110.00","35,719.00","39,097.00","66,630.00","49,813.00","57,483.00","86,043.00","80,666.00","56,549.00","55,809.00","57,407.00","46,036.00","64,945.00","72,187.00","48,294.00","54,226.00","68,253.00","60,175.00","53,061.00","51,276.00","63,499.00","39,011.00","53,200.00","52,303.00","49,794.00","49,275.00","53,851.00","57,805.00","51,106.00","70,962.00","63,254.00","48,752.00","54,711.00","53,963.00","55,052.00","46,073.00","50,088.00","36,327.00","45,543.00","51,671.00","55,300.00","42,712.00","67,737.00","53,608.00","44,903.00","47,483.00","42,627.00","33,041.00","62,519.00","55,547.00","46,830.00","54,377.00","38,225.00","43,085.00","48,807.00","43,810.00","45,261.00","50,232.00","51,668.00","37,890.00","48,328.00","29,381.00","45,035.00","42,632.00","22,302.00","44,129.00","62,388.00","35,889.00","48,543.00","34,704.00","51,395.00","39,430.00","47,410.00","46,986.00","43,632.00","39,443.00","36,813.00","47,380.00","57,392.00","53,241.00","48,052.00","49,525.00","59,563.00","35,686.00","43,887.00","43,405.00","29,734.00","46,242.00","33,627.00","35,465.00","48,937.00","39,765.00","26,516.00","66,654.00","46,914.00","59,669.00","53,847.00","46,629.00","36,830.00","46,319.00","61,770.00","35,911.00","33,476.00","38,526.00","30,347.00","47,639.00","40,191.00","37,219.00","42,412.00","46,406.00","42,491.00","50,224.00","37,040.00","39,750.00","21,751.00","32,446.00","39,736.00","32,984.00","46,662.00","45,827.00","37,829.00","42,274.00","37,080.00","36,111.00","42,801.00","41,717.00","48,049.00","62,672.00","39,345.00","52,041.00","25,630.00","49,892.00","44,645.00","39,544.00","48,689.00","36,010.00","31,921.00","64,350.00","38,940.00","50,137.00","37,583.00","43,605.00","75,843.00","40,363.00","60,422.00","37,204.00","26,194.00","39,110.00","53,418.00","34,932.00","90,986.00","34,572.00","41,853.00","43,935.00","33,813.00","48,744.00","26,047.00","45,079.00","38,238.00","46,720.00","32,026.00","29,625.00","34,669.00","35,370.00","53,047.00","38,057.00","34,592.00","44,597.00","41,988.00"
GDP_2002,"44,008.00","40,894.00","37,564.00","47,371.00","37,194.00","44,028.00","53,172.00","45,124.00","47,031.00","54,095.00","49,467.00","39,592.00","66,385.00","51,662.00","45,470.00","29,106.00","32,090.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"40,144.00","22,106.00","18,889.00","22,906.00","34,840.00","54,885.00","74,702.00","54,373.00","65,759.00","57,279.00","29,501.00","30,690.00","62,465.00","41,488.00","44,181.00","47,377.00","42,375.00","32,074.00","31,007.00","52,053.00","33,393.00","47,395.00","33,490.00","39,913.00","44,937.00","27,307.00","30,551.00","42,521.00","53,980.00","51,657.00","36,908.00","50,939.00","33,711.00","37,724.00","38,419.00","48,529.00","29,538.00","30,663.00","36,979.00","33,779.00","35,124.00","42,673.00","42,628.00","26,183.00","35,720.00","43,077.00","20,679.00","40,785.00","35,260.00","42,251.00","49,626.00","53,225.00","39,956.00","35,199.00","42,630.00","36,829.00","37,458.00","42,719.00","35,967.00","39,839.00","28,084.00","47,993.00","44,010.00","36,423.00","47,049.00","42,885.00","34,711.00","30,292.00","26,993.00","40,408.00","30,078.00","33,523.00","51,257.00","40,993.00","38,168.00","42,245.00","45,254.00","39,750.00","32,627.00","26,764.00","36,932.00","24,335.00","28,639.00","34,787.00","39,651.00","48,076.00","43,410.00","31,258.00","38,248.00","26,127.00","28,819.00","25,043.00","19,677.00","53,031.00","38,829.00","40,580.00","36,387.00","58,283.00","45,311.00","40,921.00","38,946.00","38,939.00","38,026.00","31,987.00","31,724.00","30,460.00","37,248.00","32,462.00","32,951.00","38,598.00","40,068.00","39,179.00","32,340.00","36,126.00","34,303.00","34,226.00","37,360.00","24,683.00","31,082.00","34,368.00","32,324.00","34,694.00","35,798.00","28,260.00","37,437.00","38,326.00","19,808.00","55,209.00","32,087.00","32,440.00","30,414.00","27,846.00","45,344.00","34,427.00","29,274.00","27,583.00","41,413.00","35,211.00","29,468.00","33,426.00","48,738.00","40,218.00","30,865.00","33,819.00","37,676.00","30,710.00","27,009.00","31,154.00","21,957.00","29,234.00","24,291.00","31,843.00","27,998.00","27,301.00","35,798.00","37,387.00","63,657.00","35,746.00","34,091.00","25,949.00","28,804.00","29,523.00","26,369.00","44,595.00","39,190.00","30,774.00","36,561.00","38,107.00","26,503.00","33,277.00","16,173.00","24,677.00","19,034.00","68,436.00","79,572.00","55,572.00","59,134.00","27,836.00","46,082.00","26,063.00","45,963.00","52,385.00","30,940.00","55,108.00","27,363.00","43,504.00","44,897.00","24,451.00","32,438.00","45,933.00","47,724.00","52,230.00","52,629.00","40,129.00","43,517.00","35,200.00","40,176.00","31,825.00","33,954.00","32,639.00","24,430.00","26,974.00","33,250.00","32,770.00","40,103.00","31,671.00","36,830.00","31,064.00","32,726.00","30,962.00","36,383.00","29,399.00","27,576.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"17,907.00","11,435.00","93,434.00","20,014.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"54,947.00","59,530.00","45,690.00","59,234.00","44,697.00","38,523.00","52,561.00","34,164.00","41,185.00","45,257.00","43,991.00","39,412.00","34,758.00","60,647.00","44,822.00","41,096.00","50,739.00","26,703.00","18,057.00","18,448.00","21,929.00","26,728.00","20,020.00","18,209.00","14,722.00","18,970.00","14,639.00","13,762.00","14,582.00","16,982.00","11,681.00","41,616.00","27,569.00","25,910.00",NaN,"36,990.00","21,815.00","55,626.00","39,193.00","36,802.00","39,643.00","66,269.00","50,727.00","57,654.00","88,600.00","78,484.00","56,898.00","55,749.00","54,675.00","47,145.00","64,194.00","72,248.00","48,581.00","55,207.00","68,322.00","60,501.00","55,175.00","51,625.00","62,993.00","39,520.00","52,509.00","53,771.00","50,004.00","50,007.00","54,469.00","57,803.00","52,421.00","71,647.00","63,372.00","49,374.00","54,809.00","54,200.00","55,245.00","46,852.00","50,671.00","37,386.00","45,472.00","52,097.00","56,762.00","43,003.00","64,927.00","54,504.00","44,844.00","48,479.00","43,724.00","35,455.00","60,644.00","55,488.00","48,414.00","55,193.00","37,497.00","42,087.00","49,374.00","45,308.00","44,784.00","51,527.00","52,218.00","40,178.00","48,701.00","30,011.00","46,830.00","43,336.00","22,269.00","44,324.00","61,459.00","38,027.00","50,075.00","35,482.00","52,629.00","40,560.00","47,582.00","46,806.00","43,269.00","40,010.00","38,201.00","46,296.00","58,017.00","54,272.00","49,183.00","50,508.00","60,579.00","36,098.00","45,814.00","44,290.00","29,484.00","46,517.00","34,315.00","35,909.00","50,702.00","39,697.00","28,075.00","68,302.00","49,161.00","57,151.00","52,906.00","47,543.00","37,773.00","47,902.00","63,685.00","37,342.00","33,884.00","38,117.00","27,931.00","49,232.00","40,313.00","38,563.00","39,670.00","48,393.00","39,351.00","52,282.00","37,607.00","39,967.00","22,429.00","33,614.00","38,629.00","33,215.00","47,020.00","45,606.00","38,411.00","43,163.00","38,908.00","36,804.00","43,321.00","41,954.00","50,586.00","64,982.00","39,758.00","53,094.00","26,072.00","49,198.00","45,235.00","39,409.00","48,828.00","36,449.00","32,603.00","63,927.00","40,031.00","50,515.00","38,397.00","45,402.00","69,796.00","40,372.00","60,532.00","37,072.00","27,088.00","40,141.00","54,513.00","35,574.00","93,566.00","34,825.00","43,021.00","44,248.00","32,407.00","55,656.00","27,010.00","46,846.00","35,315.00","49,395.00","34,051.00","30,974.00","34,845.00","36,593.00","51,751.00","38,723.00","34,997.00","46,856.00","44,687.00"

---

## 4. Importing SPSS, Stata, and SAS data

In [1]:
import pandas as pd
import numpy as np
import pyreadstat

In [2]:
nls97spss, metaspss = pyreadstat.read_sav('data/nls97.sav')

In [3]:
nls97spss.dtypes

R0000100    float64
R0536300    float64
R0536401    float64
R0536402    float64
R1235800    float64
R1482600    float64
R9793800    float64
R9793900    float64
R9871900    float64
R9872000    float64
R9872200    float64
R9872400    float64
S8646900    float64
S8647000    float64
S8647100    float64
S8647200    float64
S8647300    float64
S8647400    float64
S8647500    float64
S8647600    float64
S8647700    float64
S8647800    float64
T6651700    float64
U1836800    float64
U1836900    float64
U1837000    float64
U1837100    float64
U1837200    float64
U1837300    float64
U1845400    float64
U1852400    float64
U1852600    float64
U1852700    float64
U2166200    float64
U2166300    float64
U2166400    float64
U2166500    float64
U2857300    float64
U2962800    float64
U2962900    float64
U2963000    float64
Z9063900    float64
dtype: object

In [4]:
nls97spss.head().transpose()

               0       1       2       3       4
R0000100     1.0     2.0     3.0     4.0     5.0
R0536300     2.0     1.0     2.0     2.0     1.0
R0536401     9.0     7.0     9.0     2.0    10.0
R0536402  1981.0  1982.0  1983.0  1981.0  1982.0
R1235800     1.0     1.0     1.0     1.0     1.0
R1482600     4.0     2.0     2.0     2.0     2.0
R9793800   350.0   460.0     NaN     NaN     NaN
R9793900   470.0   440.0     NaN     NaN     NaN
R9871900   309.0   217.0     NaN   253.0   243.0
R9872000   310.0   280.0     NaN   216.0   235.0
R9872200   293.0   114.0     NaN   195.0   293.0
R9872400   333.0   143.0     NaN   216.0   231.0
S8646900     NaN     NaN     NaN     NaN     NaN
S8647000     NaN     NaN     NaN     NaN     NaN
S8647100     NaN     NaN     NaN     NaN     NaN
S8647200     NaN     NaN     NaN     NaN     NaN
S8647300     NaN     NaN     NaN     NaN     NaN
S8647400     NaN     NaN     NaN     NaN     NaN
S8647500     NaN     NaN     NaN     NaN     NaN
S8647600     NaN     NaN     NaN     NaN     NaN
S8647700     NaN     NaN     NaN     NaN     NaN
S8647800     NaN     NaN     NaN     NaN     NaN
T6651700     NaN     NaN     NaN     NaN     NaN
U1836800     NaN     NaN     3.0     NaN     NaN
U1836900     NaN     NaN     NaN     NaN     NaN
U1837000     NaN     NaN     NaN     NaN     NaN
U1837100     NaN     NaN     NaN     NaN     NaN
U1837200     NaN     NaN     NaN     NaN     NaN
U1837300     NaN     NaN     NaN     NaN     NaN
U1845400     NaN    14.0    16.0    13.0    12.0
U1852400     NaN     0.0     1.0     0.0     1.0
U1852600     NaN     NaN     2.0     1.0     2.0
U1852700     NaN     NaN     0.0     1.0     0.0
U2166200     NaN     NaN     NaN     NaN     NaN
U2166300     NaN     NaN     NaN     NaN     NaN
U2166400     NaN     NaN     NaN     NaN     NaN
U2166500     NaN     NaN     NaN     NaN     NaN
U2857300     NaN     NaN     NaN     NaN     NaN
U2962800     NaN     4.0     6.0     3.0     2.0
U2962900     NaN     2.0     2.0     2.0     2.0
U2963000     NaN     6.0     6.0     6.0     5.0
Z9063900    52.0     0.0     0.0     4.0    12.0

In [5]:
metaspss.variable_value_labels['R0536300'] = {0.0: 'No information', 1.0: 'male', 2.0: 'female'}

### Exploring SPSS Data Attributes and Metadata

When working with SPSS data, the metadata object contains valuable information about variables, labels, and data structure. Let's explore what attributes are available.

In [6]:
# 1. Check all available attributes of the metadata object
print("üîç Available metadata attributes:")
print("="*50)
for attr in dir(metaspss):
    if not attr.startswith('_'):  # Skip private attributes
        print(f"  üìã {attr}")

print(f"\nüìä Type of metadata object: {type(metaspss)}")

üîç Available metadata attributes:
==================================================
  üìã column_labels
  üìã column_names
  üìã column_names_to_labels
  üìã creation_time
  üìã file_encoding
  üìã file_format
  üìã file_label
  üìã missing_ranges
  üìã missing_user_values
  üìã modification_time
  üìã mr_sets
  üìã notes
  üìã number_columns
  üìã number_rows
  üìã original_variable_types
  üìã readstat_variable_types
  üìã table_name
  üìã value_labels
  üìã variable_alignment
  üìã variable_display_width
  üìã variable_measure
  üìã variable_storage_width
  üìã variable_to_label
  üìã variable_value_labels

üìä Type of metadata object: <class 'pyreadstat._readstat_parser.metadata_container'>

In [12]:
# 2. Explore variable names and labels
print("üè∑Ô∏è  Variable Names and Labels:")
print("="*50)
print(f"Total variables: {len(metaspss.column_names)}")
print(f"First 10 variable names: {metaspss.column_names[:10]}")

if hasattr(metaspss, 'column_labels') and metaspss.column_labels:
    print(f"\nVariable labels available: {len(metaspss.column_labels)} labels")
    # Show first few variable labels
    for i, label in enumerate(metaspss.column_labels[:5]):
        print(f"  {i+1}. {label}")
else:
    print("\nNo variable labels found")

üè∑Ô∏è  Variable Names and Labels:
==================================================
Total variables: 42
First 10 variable names: ['R0000100', 'R0536300', 'R0536401', 'R0536402', 'R1235800', 'R1482600', 'R9793800', 'R9793900', 'R9871900', 'R9872000']

Variable labels available: 42 labels
  1. PUBID - YTH ID CODE 1997
  2. KEY!SEX (SYMBOL) 1997
  3. KEY!BDATE M/Y (SYMBOL) 1997
  4. KEY!BDATE M/Y (SYMBOL) 1997
  5. CV_SAMPLE_TYPE 1997

In [8]:
# 3. Explore variable value labels (like the gender example)
print("üî¢ Variable Value Labels:")
print("="*50)

if hasattr(metaspss, 'variable_value_labels') and metaspss.variable_value_labels:
    print(f"Variables with value labels: {len(metaspss.variable_value_labels)}")
    
    # Show all variables that have value labels
    print("\nVariables with defined value labels:")
    for var_name in metaspss.variable_value_labels.keys():
        labels = metaspss.variable_value_labels[var_name]
        print(f"  üìä {var_name}: {len(labels)} labels")
        
    # Show detailed example for R0536300 (gender)
    if 'R0536300' in metaspss.variable_value_labels:
        print(f"\nDetailed view of R0536300 value labels:")
        for code, label in metaspss.variable_value_labels['R0536300'].items():
            print(f"  {code} ‚Üí '{label}'")
else:
    print("No variable value labels found")

üî¢ Variable Value Labels:
==================================================
Variables with value labels: 28

Variables with defined value labels:
  üìä R0536300: 3 labels
  üìä R1235800: 2 labels
  üìä R1482600: 4 labels
  üìä S8646900: 4 labels
  üìä S8647000: 4 labels
  üìä S8647100: 4 labels
  üìä S8647200: 4 labels
  üìä S8647300: 4 labels
  üìä S8647400: 4 labels
  üìä S8647500: 4 labels
  üìä S8647600: 4 labels
  üìä S8647700: 4 labels
  üìä S8647800: 4 labels
  üìä U1836800: 3 labels
  üìä U1836900: 3 labels
  üìä U1837000: 3 labels
  üìä U1837100: 3 labels
  üìä U1837200: 3 labels
  üìä U1837300: 3 labels
  üìä U1845400: 22 labels
  üìä U1852400: 5 labels
  üìä U2166200: 10 labels
  üìä U2166300: 10 labels
  üìä U2166400: 10 labels
  üìä U2166500: 10 labels
  üìä U2857300: 7 labels
  üìä U2962800: 6 labels
  üìä U2962900: 6 labels

Detailed view of R0536300 value labels:
  0.0 ‚Üí 'No information'
  1.0 ‚Üí 'male'
  2.0 ‚Üí 'female'

In [9]:
# 4. Check for missing values information
print("‚ùì Missing Values Information:")
print("="*50)

if hasattr(metaspss, 'missing_ranges') and metaspss.missing_ranges:
    print(f"Variables with missing value ranges: {len(metaspss.missing_ranges)}")
    for var, ranges in list(metaspss.missing_ranges.items())[:5]:
        print(f"  {var}: {ranges}")
else:
    print("No missing value ranges defined")

if hasattr(metaspss, 'variable_display_width'):
    print(f"\nDisplay width info available for {len(metaspss.variable_display_width)} variables")

if hasattr(metaspss, 'variable_measure'):
    print(f"Variable measure info available for {len(metaspss.variable_measure)} variables")
    # Show measurement levels
    measures = list(metaspss.variable_measure.values())[:10]
    print(f"Sample measurement levels: {set(measures)}")

‚ùì Missing Values Information:
==================================================
No missing value ranges defined

Display width info available for 42 variables
Variable measure info available for 42 variables
Sample measurement levels: {'scale', 'nominal'}

In [10]:
# 5. Create a comprehensive metadata summary function
def explore_spss_metadata(meta):
    """
    Comprehensive function to explore all SPSS metadata attributes
    """
    print("üìã COMPREHENSIVE SPSS METADATA SUMMARY")
    print("="*60)
    
    # Basic info
    print(f"üîπ Total variables: {len(meta.column_names)}")
    print(f"üîπ Metadata type: {type(meta)}")
    
    # Available attributes
    attrs = [attr for attr in dir(meta) if not attr.startswith('_')]
    print(f"üîπ Available attributes: {len(attrs)}")
    
    # Check each important attribute
    important_attrs = ['column_names', 'column_labels', 'variable_value_labels', 
                      'missing_ranges', 'variable_display_width', 'variable_measure',
                      'file_label', 'file_encoding']
    
    print(f"\nüìä DETAILED ATTRIBUTE ANALYSIS:")
    for attr in important_attrs:
        if hasattr(meta, attr):
            value = getattr(meta, attr)
            if value:
                if isinstance(value, dict):
                    print(f"  ‚úÖ {attr}: {len(value)} items")
                elif isinstance(value, list):
                    print(f"  ‚úÖ {attr}: {len(value)} items")
                else:
                    print(f"  ‚úÖ {attr}: {value}")
            else:
                print(f"  ‚ö™ {attr}: Empty/None")
        else:
            print(f"  ‚ùå {attr}: Not available")

# Run the comprehensive analysis
explore_spss_metadata(metaspss)

üìã COMPREHENSIVE SPSS METADATA SUMMARY
============================================================
üîπ Total variables: 42
üîπ Metadata type: <class 'pyreadstat._readstat_parser.metadata_container'>
üîπ Available attributes: 24

üìä DETAILED ATTRIBUTE ANALYSIS:
  ‚úÖ column_names: 42 items
  ‚úÖ column_labels: 42 items
  ‚úÖ variable_value_labels: 28 items
  ‚ö™ missing_ranges: Empty/None
  ‚úÖ variable_display_width: 42 items
  ‚úÖ variable_measure: 42 items
  ‚ö™ file_label: Empty/None
  ‚úÖ file_encoding: UTF-8

In [11]:
nls97spss['R0536300'].map(metaspss.variable_value_labels['R0536300']).value_counts(normalize=True)

R0536300
male      0.51191
female    0.48809
Name: proportion, dtype: float64